services:
    curler.sonata_drag_and_drop_upload.admin.extension.drag_and_drop_upload:
        class: Curler\SonataDragAndDropUploadBundle\Admin\Extension\DragAndDropUploadAdminExtension
        tags:
            - { name: sonata.admin.extension, target: sonata.media.admin.media }

    curler.sonata_drag_and_drop_upload.admin.extension.gallery:
        class: Curler\SonataDragAndDropUploadBundle\Admin\Extension\GalleryAdminExtension
        calls:
            - [setGalleryManager, ['@sonata.media.manager.gallery']]

    Curler\SonataDragAndDropUploadBundle\Admin\Extension\DragAndDropUploadAdminExtension:
        alias: curler.sonata_drag_and_drop_upload.admin.extension.drag_and_drop_upload

    Curler\SonataDragAndDropUploadBundle\Admin\Extension\GalleryAdminExtension:
        alias: curler.sonata_drag_and_drop_upload.admin.extension.gallery