services:
    curler.sonata_drag_and_drop_upload.controller.drag_and_drop_upload:
        class: Curler\SonataDragAndDropUploadBundle\Controller\DragAndDropUploadController
        arguments:
            - '@sonata.media.manager.media'
            - '@sonata.media.manager.gallery'
            -
        tags: ['controller.service_arguments']


    Curler\SonataDragAndDropUploadBundle\Controller\DragAndDropUploadController:
        alias: curler.sonata_drag_and_drop_upload.controller.drag_and_drop_upload
        public: true