services:
    smart_media.sonata_drag_and_drop_upload.controller.drag_and_drop_upload:
        class: SmartMedia\SonataDragAndDropUploadBundle\Controller\DragAndDropUploadController
        arguments:
            - '@sonata.media.manager.media'
            - '@sonata.media.manager.gallery'
            -
        tags: ['controller.service_arguments']


    SmartMedia\SonataDragAndDropUploadBundle\Controller\DragAndDropUploadController:
        alias: smart_media.sonata_drag_and_drop_upload.controller.drag_and_drop_upload
        public: true